import './globals.css'
import Nav from "./components/Nav";
import { getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className='mx-12'>
      <Nav user={session?.user} expires={session?.expires as string} />
        {children}
        </body>
    </html>
  )
}
